DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name)
);

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email)
);

DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000) NOT NULL,
    category_id        BIGINT NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000) NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id       BIGINT NOT NULL,
    lat                FLOAT NOT NULL,
    lon                FLOAT NOT NULL,
    paid               BOOLEAN NOT NULL,
    participant_limit  INTEGER NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN NOT NULL,
    state              VARCHAR(10) NOT NULL,
    title              VARCHAR(120) NOT NULL,
    CONSTRAINT fk_event_to_category FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT fk_event_to_user FOREIGN KEY(initiator_id) REFERENCES users(id)
);

DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_id     BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    status       VARCHAR(10) NOT NULL,
    CONSTRAINT fk_request_to_event FOREIGN KEY(event_id) REFERENCES events(id),
    CONSTRAINT fk_request_to_user FOREIGN KEY(requester_id) REFERENCES users(id),
    CONSTRAINT uq_request_per_event UNIQUE (event_id, requester_id)
);

DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;

CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR(50) NOT NULL,
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilation_events (
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_comp_event PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_comp_event_to_comp FOREIGN KEY(compilation_id) REFERENCES compilations(id),
    CONSTRAINT fk_comp_event_to_event FOREIGN KEY(event_id) REFERENCES events(id)
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS comments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text         VARCHAR(1000) NOT NULL,
    author_id    BIGINT NOT NULL,
    event_id     BIGINT NOT NULL,
    created_on   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_comment_to_user FOREIGN KEY(author_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_to_event FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE
);